### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by blahdidbert** [JGeek00/droid-hole#10]
Hello,

Whenever I put in the information, I receive "Failed: Unknown Error". Putting in other information into the subroutine shows "Failed: API Key is invalid."

Is there a way to get more details of the error messages?

Droidhole Version: v3.1.2
Pi-hole: v5.14.2 
FTL: v5.20 
Web Interface: v5.18

**Comment by JGeek00** [comment]
Do you have any special configuration (reverse proxy or similar)? Unfortunately I didn't implemented a logging system on this app.

Make sure that on the top of the new connection screen you have the exact same URL as you use for the web admin panel.

**Comment by blahdidbert** [comment]
No special implementation and everything is hitting the way it should. Do we have any recommendations on further troubleshooting?

Below are some examples of it helps.

![Screenshot_20221224-102647](https://user-images.githubusercontent.com/17502096/209442702-06f793f3-d69a-4224-bf7d-eae2c043f394.jpg)
![Screenshot_20221224-102658](https://user-images.githubusercontent.com/17502096/209442703-3331f37d-9f45-4aa0-9779-f5d89bb5a920.jpg)

Token is good which is making this weirder for me. If we don't have any other routes, no worries at all.

**Comment by JGeek00** [comment]
I would need to add a logging system to know what's happening.

**Comment by JGeek00** [comment]
I have pushed a new build to Google Play. I don't know if Google will approve it soon because this days are different. If you want to get the update now, you can download the apk from the releases section of the repository. Also you don't need to add the ``/admin`` on path.

Just after seeing an error on the login screen, go to Settings > Advanced settings > App logs and tap on the share button. This will copy the logs into the clipboard, then paste it here.

**Comment by robaudis** [comment]
I noticed my app started failing to connect to a previously configured pihole that was working correctly. I have my pihole running in a docker container which automatically updates (not really best practice I know). Perhaps this PR is relevant as it was included in the latest release https://github.com/pi-hole/AdminLTE/pull/2411 ?

**Comment by JGeek00** [comment]
Could you send me what are you receiving from this endpoint ``[base url]/admin/api.php`` and from this endpoint ``[base_url]/admin/api.php?auth=${server.token}&enable=0``?

**Comment by blahdidbert** [comment]
![Screenshot_20221224_183920](https://user-images.githubusercontent.com/17502096/209457529-29b62ec5-7945-4bef-b4a0-ed24ddbf9cd8.jpg)
![Screenshot_20221225_000719](https://user-images.githubusercontent.com/17502096/209457532-2459c36e-4d4e-4c8f-b6b5-97e96e3fefd1.jpg)

**Comment by robaudis** [comment]
From the first URL I get:
`[]`

From the second, with my API token I get:
`{"status":"enabled"}`

**Comment by JGeek00** [comment]
> ![Screenshot_20221224_183920](https://user-images.githubusercontent.com/17502096/209457529-29b62ec5-7945-4bef-b4a0-ed24ddbf9cd8.jpg)
> 
> ![Screenshot_20221225_000719](https://user-images.githubusercontent.com/17502096/209457532-2459c36e-4d4e-4c8f-b6b5-97e96e3fefd1.jpg)
> 
> 

On the first URL you have to remove the first $ (if it's not included in the API token string)z

**Comment by JGeek00** [comment]
> From the first URL I get:
> 
> `[]`
> 
> 
> 
> From the second, with my API token I get:
> 
> `{"status":"enabled"}`

That's weird. You are not receiving anything from the base endpoint. Try calling that same endpoint but adding ?auth=[your token].

**Comment by blahdidbert** [comment]
I am getting the same response as @robaudis after I corrected the query.

![Screenshot_20221225_080718](https://user-images.githubusercontent.com/17502096/209469160-bb875774-d336-4bd3-ac60-ff8a47076942.jpg)

**Comment by robaudis** [comment]
With the first URL and appending the auth parameter I get the same response:
`[]`

**Comment by JGeek00** [comment]
Please try with this URL replacing server_address and token.

``[server_address]/admin/api.php?auth=[token]&summaryRaw&topItems&getForwardDestinations&getQuerySources&topClientsBlocked&getQueryTypes``

**Comment by JGeek00** [comment]
Please try this version and let me know if it's fixed.

[app-release.apk.zip](https://github.com/JGeek00/droid-hole/files/10303905/app-release.apk.zip)

**Comment by JGeek00** [comment]
Glad to read that!

Thank you for using the app and hope you are enjoying it. Merry Christmas and enjoy this holidays with your family and friends :-)

**Comment by JGeek00** [comment]
Fixed on v3.1.4.
