### ISSUE TITLE
Perform a search from log details 

### ISSUE THREAD

**Issue by HyperCriSiS** [JGeek00/droid-hole#12]
Hi,

Can you add a button in the log details to perform a search?
This would speed up research.

Best regards
Hyper

**Comment by JGeek00** [comment]
I don't really know what you are referring to. What content do you want to search from the details screen?

**Comment by HyperCriSiS** [comment]
Hi,

sorry I missed your response.
I just want to make an internet search from the log details screen with the domain name which was blocked/allowed.
This would help a lot when trying to find more information about a certain request.

Thanks
Hyper

**Comment by JGeek00** [comment]
Sure. I can do that.

**Comment by JGeek00** [comment]
Added on v3.7.0.

**Comment by HyperCriSiS** [comment]
Thank you, works perfectly! But maybe change the search engine to Startpage?
Startpage has the same results but much more privacy :)
