### ISSUE TITLE
Disable Pi-hole for certain device 

### ISSUE THREAD

**Issue by HyperCriSiS** [JGeek00/droid-hole#13]
Hi,
Actually it is only possible to temporarily disable Pi-hole for all devices.
It would be helpful to be able to do this just for one certain device. But I assume this is a Pi-hole limitation? Maybe via an automatically temporary created group?

Best regards
Hyper

**Comment by JGeek00** [comment]
Sorry but that's not possibleZ Pi-hole doesn't allow that.
