### ISSUE TITLE
[BUG] Total blocked/not blocked queries for a given time period show identical numbers

### ISSUE THREAD

**Issue by eroc1990** [JGeek00/droid-hole#16]
When reviewing a specific time slice's queries to see how many queries were permitted and how many were blocked, both numbers show the same thing, instead of the correct numbers that correspond to the number of not blocked vs blocked queries. The screenshot included shows this occurring.

![Screenshot_20230126-115853~2.png](https://user-images.githubusercontent.com/13401635/214900386-a098606d-b8fe-47bf-aade-1beaf4d73309.png)

**Comment by JGeek00** [comment]
Fixed on v3.4.0.
