### ISSUE TITLE
Add support for basic auth

### ISSUE THREAD

**Issue by maxthegold** [JGeek00/droid-hole#17]
I need to be able to sign in to my web server, any chance of adding this facility.

**Comment by JGeek00** [comment]
Hi. Could you give me more details about that?

**Comment by maxthegold** [comment]
I am using Nginx on a Raspberry Pi 4 (latest version of Raspian OS and Nginx). The default setting for Nginx is to implement security with the following instructions in the .conf,

auth_basic "Restricted";                                     # For Basic Auth

auth_basic_user_file /etc/nginx/.htpasswd;  # For Basic Auth

This means that when you try to access Pihole, Nginx requests the user and password that you have set up in the .htpasswd file.

Hope this makes sense. It is possible to remove this Nginx option, but security is always a good idea and I thought it might be a feature you would like to include in your program. 

 

Mark

**Comment by JGeek00** [comment]
So you have a basic auth on top of the API right? Will work on adding support for that.

**Comment by maxthegold** [comment]
Yes, that's right. Nginx is requesting a userid and password before it lets
me access pihole/admin.

**Comment by JGeek00** [comment]
Hi. Please, try this version and let me know if it's working for your configuration.

[3.6.0_beta.apk.zip](https://github.com/JGeek00/droid-hole/files/10777958/3.6.0_beta.apk.zip)

**Comment by maxthegold** [comment]
Yes that’s good, I can sign on now. The only problem with it is when I try to access Logs or Domains it says ‘…couldn’t be loaded’.

 

Mark.

**Comment by maxthegold** [comment]
Juan,

                For the sake of completeness I have tested the app with an invalid user/password and with no user/password. Both fail as expected. I have also tested the good user/password as default and non default and both work as expected.

 

Mark.

**Comment by JGeek00** [comment]
Hi. Please, try this version.

[3.6.0_beta2.apk.zip](https://github.com/JGeek00/droid-hole/files/10787772/3.6.0_beta2.apk.zip)

**Comment by maxthegold** [comment]
Yes, that's done the trick, all seems to be working now.

Thanks,
Mark.

**Comment by JGeek00** [comment]
Great! Soon I will push a new update to Google Play adding that functionality.

**Comment by maxthegold** [comment]
Great, thanks!

**Comment by JGeek00** [comment]
Added on v3.6.0.

**Comment by maxthegold** [comment]
Great, thanks!
