### ISSUE TITLE
UI bugs on home page

### ISSUE THREAD

**Issue by hofmmaxi** [JGeek00/droid-hole#19]
There are currently two UI bugs on the home page:

All items below the client activity chart are completely unaligned:
![Screenshot_20230309-235506.png](https://user-images.githubusercontent.com/61088478/224179403-4f8a4431-3e73-422a-98a7-531d8a586389.png)

Secondly, if you're holding a point on this client chart, the chart scale and the client legend get shifted down and no infos about this time is shown (time or requests per client):
![Screenshot_20230309-235521.png](https://user-images.githubusercontent.com/61088478/224179404-a1a7414e-f8b0-4f3b-bbe2-a2106526de67.png)

**Comment by JGeek00** [comment]
Hi. I have been investigating that issues.

I think I have solved the misalignment issue.
![Screenshot_1678990204](https://user-images.githubusercontent.com/47545344/225713257-febb6a95-0fa0-4650-a767-4f406f956b86.png)

Regarding the other issue, I don't have any way to reproduce it. My primary DNS server is AdGuard Home, not Pi-hole. I have a Raspberry Pi running Pi-hole with only one client just to maintain this application.
If you can send me what you are receiving from this endpoint it would be helpful: ``{{url}}/admin/api.php?auth={{api_key}}&overTimeDataClients=&getClientNames``.

**Comment by JGeek00** [comment]
Alignment issue fixed on v3.8.0. For the other bug, please open a new issue.
