### ISSUE TITLE
General Whitelist/Blacklist handling

### ISSUE THREAD

**Issue by HyperCriSiS** [JGeek00/droid-hole#20]
Hi,

When an address is white-/blacklisted via the button in log details It would be more convenient if this is a toggle.
In the Whitelist and Blacklist it would be helpful to have a full text search. 

Thanks,
Hyper

**Comment by JGeek00** [comment]
I think it's not a good idea to add there a toggle, because that's not something that you can enable or disable. The search on lists I think it's a good idea.

**Comment by JGeek00** [comment]
Search added on v3.8.0.

**Comment by HyperCriSiS** [comment]
I sometimes enable an address just for one time, this is why this toggle would help. If blocked I just whitelist for a brief moment and could block it again in no time with the same button.

**Comment by HyperCriSiS** [comment]
> Search added on v3.8.0.

Dude, you are fast!! :D Thanks so much.

**Comment by JGeek00** [comment]
> I sometimes enable an address just for one time, this is why this toggle would help. If blocked I just whitelist for a brief moment and could block it again in no time with the same button.
> 
> 

The problem is that the add to whitelist / remove from whitelist endpoint it's not intended to be used to block a domain momentarily. It would be useful to block a domain just for some time but that's a feature that has to be added on Pi-hole itself. I could change that button that it's on the log details screen to say "Remove from whitelist" instead of "Add to blacklist" when a domain is already on a list.

**Comment by HyperCriSiS** [comment]
Yeah that sounds good 👍

**Comment by HyperCriSiS** [comment]
> > I sometimes enable an address just for one time, this is why this toggle would help. If blocked I just whitelist for a brief moment and could block it again in no time with the same button.
> 
> The problem is that the add to whitelist / remove from whitelist endpoint it's not intended to be used to block a domain momentarily. It would be useful to block a domain just for some time but that's a feature that has to be added on Pi-hole itself. I could change that button that it's on the log details screen to say "Remove from whitelist" instead of "Add to blacklist" when a domain is already on a list.

Also it would be possible if the app handles it itself just with a simple timer.
