### ISSUE TITLE
Log filter - fast filter buttons

### ISSUE THREAD

**Issue by HyperCriSiS** [JGeek00/droid-hole#21]
Hi again,

Actually the log offers detailed filters, which is good, but most times I just want to filter fast for allowed or blocked entries. Can you maybe add buttons in the logs top bar for quick filter allowed/blocked entries?

Thanks,
Hyper

**Comment by JGeek00** [comment]
Let me think about that. I think it's useful but don't want to have the top bar crowded of icons. Maybe I need to add a context menu 🤔

**Comment by HyperCriSiS** [comment]
Maybe inside the filter menu on the top left and right :)
Or maybe just use one icon which would not clutter the top bar too much and cycle through allowed/blocked/all.

**Comment by JGeek00** [comment]
Added on v3.9.0.
