### ISSUE TITLE
Relax IP/Domain Validation

### ISSUE THREAD

**Issue by d1vanloon** [JGeek00/droid-hole#22]
# Summary

When adding a new connection, the validation on the "IP address or domain" field is too restrictive. For example, my Pi-Hole is reachable via a single-word hostname (e.g. `http://pihole`). This value, though correct, is rejected by the field validation.

# Suggested Change

Relax the validation on the "IP address or domain" field when adding a new connection to allow single-word hostnames.

**Comment by JGeek00** [comment]
Hi. Please check if this works for you.

[app-release.apk.zip](https://github.com/JGeek00/droid-hole/files/11066618/app-release.apk.zip)

**Comment by JGeek00** [comment]
Changed on v3.9.0.
