### ISSUE TITLE
Feature Request: DHCP config/lease tab

### ISSUE THREAD

**Issue by pesaventofilippo** [JGeek00/droid-hole#27]
It would be cool to have a tab in the app to see or manage active and static DHCP leases (if the API allows it).
Great work btw!

**Comment by JGeek00** [comment]
I have been checking it and unfortunately the API does not support it. The DHCP configuration comes loaded into the fields from the server with the rest of the page, that means the configuration values are not fetched from the API, and I cannot request that values to the API to load them into DroidHole. Glad you like the app.
