### ISSUE TITLE
Linux version isn't functional

### ISSUE THREAD

**Issue by t3dium** [JGeek00/droid-hole#31]
I downloaded the tar.gz in the releases section and ran the executable, but it keeps returning the below error when adding servers:
![image](https://github.com/JGeek00/droid-hole/assets/83690012/c9f61a18-1465-4e74-8d19-77a09db41b43)

On android I entered the exact same settings and it worked.

The linux app also doesn't appear to be making any network connections at all, looking at my firewall. 

**OS**: fedora workstation
**App Version:** 4.0.0

**Comment by JGeek00** [comment]
Fixed on v4.0.1.
