### ISSUE TITLE
Logs - clicking search does not move focus

### ISSUE THREAD

**Issue by HyperCriSiS** [JGeek00/droid-hole#33]
Hi,

when you click on the search button in the logs, the focus is not moved to the search bar.
An additional click in the search bar is needed.
Can you change that? :grinning:

Regards
Hyper

**Comment by JGeek00** [comment]
You mean autofocus right?

**Comment by HyperCriSiS** [comment]
> You mean autofocus right?

An additional click is needed to make the keyboard appear.

**Comment by JGeek00** [comment]
Fixed on v4.0.5.
