### ISSUE TITLE
Translation into other languages

### ISSUE THREAD

**Issue by Akszyn** [JGeek00/droid-hole#34]
Polish language is missing but I will be happy to help translate so please link to a folder where I can add the missing language

**Comment by JGeek00** [comment]
Hi @Akszyn just copy the content of [this file](https://github.com/JGeek00/droid-hole/blob/master/lib/l10n/app_en.arb) into a new file, translate the values of the right and upload the translated file here.

**Comment by Akszyn** [comment]
Please make this translation available as a beta version of the application because you can always correct something easier

**Comment by Akszyn** [comment]
@JGeek00 is there something wrong with my translation that it has not been implemented?

**Comment by JGeek00** [comment]
@Akszyn please check the merge request. You deleted the app_en.arb file and that file must not be deleted.

**Comment by JGeek00** [comment]
Pull request merged. Thank you.

**Comment by Akszyn** [comment]
How to locate a line in the code that I would like to improve? because the translation does not fit the function for which it is responsible

**Comment by Akszyn** [comment]
I noticed a few mistakes at the arrangement of subtitles marked in yellow 
![Screenshot_2023-09-23-22-53-57-854-edit_com jgeek00 droid_hole](https://github.com/JGeek00/droid-hole/assets/57450821/eaa562e2-54f8-4678-b369-adab24d667d6)

**Comment by JGeek00** [comment]
@Akszyn yeah, no problem. The beta 2 will be available in a few hours.

**Comment by Akszyn** [comment]
@JGeek00 Thank you for your quick response and in your free time please improve the centering the text I mentioned earlier that overlaps the pictures does not fit in and goes behind the screen

**Comment by JGeek00** [comment]
Translation added on v4.1.0.

**Comment by Akszyn** [comment]
It already looks better, but it needs some minor tweaks in the centering of the text 
![Screenshot_2023-10-12-22-47-34-977-edit_com jgeek00 droid_hole](https://github.com/JGeek00/droid-hole/assets/57450821/b19a4472-aa0b-4f42-bb95-935c26794223)
What needs to be improved I have marked again in yellow
