### ISSUE TITLE
DroidHole on Windows x64 Won't Start

### ISSUE THREAD

**Issue by TKruzze** [JGeek00/droid-hole#37]
I'm enjoying DroidHole on my Android device and thought I'd try it on Windows. However, the app won't even launch on Windows and gives the following error:

droid-hole.exe - System Error
The code execution cannot proceed because local_auth_windows_plugin.dll was  not found. Reinstalling the program may fix this problem.

Is there some sort of Flutter plugin that must be installed on Windows prior to it working?

**Comment by JGeek00** [comment]
Will be fixed on the next stable release.

**Comment by JGeek00** [comment]
Fixed on v4.1.0.
