### ISSUE TITLE
Remove Clients with No Requests

### ISSUE THREAD

**Issue by adharc** [JGeek00/droid-hole#4]
When selecting a time within the Client activity graph, all clients are shown that have queried a domain in the last 24 hours rather than the chosen time.

Clients that have no requests at that time take more space than active clients.  

![droid-hole](https://user-images.githubusercontent.com/112933115/189488454-82d6f65d-9e70-4e26-995f-e6ea967062e0.png)

**Comment by JGeek00** [comment]
Hi! Thanks for the feedback. I just have figured out how to hide that 0 values. I will push an update for the application adding an option on the app's settings to hide that values.

**Comment by JGeek00** [comment]
I have just submitted the update to the Google Play Store a moment ago. It should be available in a few hours.
