### ISSUE TITLE
[UI] Navigation Bar 

### ISSUE THREAD

**Issue by McBaumwolle** [JGeek00/droid-hole#45]
Just a small detail, I noticed the navigation bar background is not the same as the app background. 

Can be easily fixed I think but it's a very small detail. 
https://docs.expo.dev/versions/latest/sdk/navigation-bar/

![Screenshot_20240201-133354.png](https://github.com/JGeek00/droid-hole/assets/67203883/c8c11c4d-b01a-4da8-a4ef-390c568083e5)

**Comment by JGeek00** [comment]
Changed for the next update.
