### ISSUE TITLE
Base path

### ISSUE THREAD

**Issue by jvandenbroek** [JGeek00/droid-hole#6]
Could you add an option to provide a base path? E.g. https://domain/pihole. Thanks!

**Comment by JGeek00** [comment]
I don't understand what is your request and what do you mean with base path. Are you asking for connecting to your pihole using a domain?

**Comment by jvandenbroek** [comment]
No, just an option to provide a base / sub / root path, however you want to call it :-) I've pihole running behind a reverse proxy, which means I do not access it like as http://IP/admin but https://ip

**Comment by JGeek00** [comment]
The application composes the URL on this way: `${server.address}/admin/index.php`.
What you input on the domain/IP field is combined with what you input on the port field (if it's not empty), and then added to the rest of the URL. So in your case, if you input "https://ip/pihole" on the domain/IP field, and leave the port field empty, the result URL will look this: "https://ip/pihole/admin/index.php".

**Comment by JGeek00** [comment]
I have published a new update on Google Play. Let me know if that works for you.

**Comment by jvandenbroek** [comment]
Excellent, it works as expected! Thanks!
